### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by PhamQuocHuy1101** [tanmayGIT/Document-Attribute-Classification#1]
Hi @tanmayGIT , I am interested in this domain. Can you share with me the dataset? Thank you so much.

**Comment by anoynymREVIEW** [comment]
Yes, you can get it from here (the segmented words and patches which are used in the paper):
http://l3i-share.univ-lr.fr/L3iTextCopies-WordPatches/L3iTextCopies-WordPatches.html

The full document images dataset is here : 
http://navidomass.univ-lr.fr/TextCopies/

**Comment by PhamQuocHuy1101** [comment]
@anoynymREVIEW  Thank you so much.
